New website design
looplanguage/looplanguage.github.io pull request #37
Opened 2021-11-09 14:01 UTC by manontheresa

This is a work in progress. Do not merge yet!

2021-11-23 15:56 UTC, manontheresa commented
Hi @kanersps & @WouterPennings , 
I don't know if everything went well, but if so... please review the navbar changes! Much appreciated. Thanks 😁

2021-11-23 16:48 UTC, WouterPennings requested changes
Very nice start. But there a some inconsistencies with padding at the header with different screen widths.
It is hard to explain in a comment, but when making the screen narrower the padding gets smaller (at tablet mode). When you get to mobile view it suddenly gets bigger again.
I personally like the thinner navbar more, the spacings at the desktop view are quite big. It takes up a lot of space right now.
(and the logo on the smallest view at dark made, is a dark version of the logo, so it has hard to see)

The last thing is that: On the deploy preview from Netlify, the logo does not render. When I run it locally it is fine. Might only be a problem on the deploy preview from netlify. idk
Nice start!

2021-11-29 12:34 UTC, manontheresa commented
The deploy mode of Netlify probably still doesn't work, I don't know why... When I Googled the question, I was not the only one experiencing the issue. 

Hopefully, it isn't a big problem... Also, thanks for reviewing the code (again). Would love to hear the feedback points! Have a nice day 😄

2021-11-29 12:59 UTC, kanersps requested changes

2021-11-29 12:59 UTC, kanersps commented on src/theme/Navbar.js
> +        var darkModeCSS = document.getElementById("lightMode");
We're in React and therefore really don't want to manually change state like this. Take a look at https://reactjs.org/docs/hooks-state.html on how you could improve this.

A general rule is to never modify the document like this.

2021-11-29 12:59 UTC, kanersps commented on src/theme/Navbar.js
> +        console.log(isDarkTheme)
Logging should be removed from final builds

2021-11-29 12:59 UTC, kanersps commented on src/theme/Navbar.js
> +            darkModeCSS.classList.remove("darkMode");
We're in React and therefore really don't want to manually change state like this. Take a look at https://reactjs.org/docs/hooks-state.html on how you could improve this.

A general rule is to never modify the document like this.

2021-11-29 12:59 UTC, kanersps commented on src/theme/Navbar.js
> +            document.getElementById('mobLogo').src="../../static/img/logoLightMode.svg";
There are two issues here, the first being just like previous comments that you're editing the document "straight up". Which like said previously will make React not know about the changes. But the second issue here is you're also setting something to a relative path. Which won't work properly either. Use React's (& ES6's features) by importing the relevant static images.

Take a look at: https://stackoverflow.com/questions/43823289/how-to-import-image-svg-png-in-a-react-component

2021-11-29 12:59 UTC, kanersps commented on src/theme/Navbar.js
> +            document.getElementsByClassName('githubLogo')[0].src="../../static/img/GithubWhite.png";
Again, don't edit pages like this. Use states: https://reactjs.org/docs/hooks-state.html

A guide for using states can be found here: https://reactjs.org/docs/state-and-lifecycle.html

2021-11-29 12:59 UTC, kanersps commented on src/theme/Navbar.js
> +    <div id="topNav" class="navbar__items navbar__items--right navItemsRight">
We're in React, allowing us to use "CSS Modules" which generally are more expressive then importing straight CSS files and using classes (as we don't know which stylesheet will implement these classes).

Take a look at https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/ on how this can be improved.

2021-11-29 12:59 UTC, kanersps commented on src/theme/Navbar.js
> +    <ul id="navItemsLeft" class="navbar__items--left resMob">
Take a look at the CSS modules. This will make styling a lot easier and allow you to easily see where styles are coming from. This is also able to avoid the large class names. As you can have multiple stylesheets which have the same class in them on the same page.

2021-11-29 12:59 UTC, kanersps commented on src/theme/Navbar.js
> +            <a class="navItem" href="https://looplang.org/docs/intro"><li>Docs</li></a>
Absolute links are not a good idea, use relative links instead. See https://www.seoquake.com/blog/relative-or-absolute-urls/ for a bit more info.

A general rule is to always use relative links when you're linking to internal websites. For example change "https://looplang.org/docs/intro" to "/docs/intro"

2021-11-29 12:59 UTC, kanersps commented on src/theme/Navbar.js
> +            <a class="navItem" href="https://looplang.org/blog"><li>Updates</li></a>
Absolute links are not a good idea, use relative links instead. See https://www.seoquake.com/blog/relative-or-absolute-urls/ for a bit more info.

A general rule is to always use relative links when you're linking to internal websites. For example change "https://looplang.org/docs/intro" to "/docs/intro"

2021-11-29 13:02 UTC, kanersps requested changes

2021-11-29 13:02 UTC, kanersps commented on src/theme/Navbar.js
> +    <img id="mobLogo" class="navItem loopLogo logoSize" src="../../static/img/logoLightMode.svg"/>
The reason that the logo doesn't work in preview mode is due to the way the logo is referenced.

Take a look at https://create-react-app.dev/docs/adding-images-fonts-and-files/ on how this should be changed.

2021-12-07 17:19 UTC, WouterPennings requested changes
The navbar looks good, and functions like it is supposed to do now.

But the bug where you cannot go to certain documentation pages is still there (Examples: [Safety](http://localhost:3000/docs/concepts/types/safety), [Enum](http://localhost:3000/docs/concepts/enum)) I do not have the knowledge to know why, @kanersps might know.

Oh, I fixed a small import bug. You had 'h'  instead of 'H'.

2022-01-20 22:09 UTC, WouterPennings approved these changes
Mooi gedaan!

2022-01-20 22:10 UTC, merged